### ISSUE TITLE
회원 탈퇴 실패

### ISSUE THREAD

**Issue by NAMU1105** [DSM-Portfolist/Portfolist-Front#128]
![image](https://user-images.githubusercontent.com/47317129/154029601-3b544782-52b1-4432-b351-30ac77f6dbb9.png)

안녕하세요,

현재 회원탈퇴가 안 되고 있습니다.

**Comment by silverbeen** [comment]
네!! 오류 수정했습니다.
이슈 남겨주셔서 감사합니다 😊

**Comment by silverbeen** [comment]
이메일 유저, 깃허브 유저 모두 회원 탈퇴가 가능하도록 이슈 수정하였습니다.
